Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -26,6 +26,14 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
+      - name: Show Current Directory and Files
+        run: |
+          echo "Current directory: $(pwd)"
+          echo "Listing contents:"
+          ls -la
+          echo "Showing terraform.tfvars if exists:"
+          cat terraform.tfvars || echo "terraform.tfvars not found"
+
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v3
         with:
